import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1751500383285 implements MigrationInterface {
    name = 'Migrations1751500383285'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "member_based_event_item" DROP CONSTRAINT "FK_member_based_event_item_event"`);
        await queryRunner.query(`ALTER TABLE "event" DROP CONSTRAINT "FK_event_camp"`);
        await queryRunner.query(`ALTER TABLE "event_item" DROP CONSTRAINT "FK_event_item_event"`);
        await queryRunner.query(`ALTER TABLE "result_item" DROP CONSTRAINT "FK_result_item_result"`);
        await queryRunner.query(`ALTER TABLE "result_item" DROP CONSTRAINT "FK_result_item_event_item"`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" DROP CONSTRAINT "FK_result_member_based_item_result"`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" DROP CONSTRAINT "FK_result_member_based_item_event_item"`);
        await queryRunner.query(`ALTER TABLE "result" DROP CONSTRAINT "FK_result_club"`);
        await queryRunner.query(`ALTER TABLE "result" DROP CONSTRAINT "FK_result_event"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_member_based_event_item_event"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_event_camp"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_event_item_event"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_result_item_result"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_result_item_event_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_result_member_based_item_result"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_result_member_based_item_event_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_result_club"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_result_event"`);
        await queryRunner.query(`CREATE TABLE "member_characteristic" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "value" integer NOT NULL, "matchCount" integer NOT NULL DEFAULT '0', "clubId" integer, CONSTRAINT "PK_4c476ab91f950996e45c67a047a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "club" DROP COLUMN "slogan"`);
        await queryRunner.query(`ALTER TABLE "club" DROP COLUMN "foundationDate"`);
        await queryRunner.query(`ALTER TABLE "club" ADD "participantsCount" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "club" ADD "guestsCount" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "club" ADD "minorsCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "club" ADD "economsCount" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "club" ADD "companionsCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "club" ADD "registrationFee" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "club" ADD "isPaid" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "club" ADD "campId" integer`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "PK_user"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "member_based_event_item" DROP CONSTRAINT "PK_member_based_event_item"`);
        await queryRunner.query(`ALTER TABLE "member_based_event_item" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "member_based_event_item" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "member_based_event_item" ADD CONSTRAINT "PK_99592168c7bd73e9366b2b05f0e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "member_based_event_item" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "member_based_event_item" ADD "eventId" integer`);
        await queryRunner.query(`ALTER TABLE "event" DROP CONSTRAINT "PK_event"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "event" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event" ADD CONSTRAINT "PK_30c2f3bbaf6d34a55f8ae6e4614" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "event" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "event" ALTER COLUMN "maxScore" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "campId"`);
        await queryRunner.query(`ALTER TABLE "event" ADD "campId" integer`);
        await queryRunner.query(`ALTER TABLE "event_item" DROP CONSTRAINT "PK_event_item"`);
        await queryRunner.query(`ALTER TABLE "event_item" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "event_item" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_item" ADD CONSTRAINT "PK_0b8a384c1ee5dc33993b3004ae4" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "event_item" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "event_item" ADD "eventId" integer`);
        await queryRunner.query(`ALTER TABLE "result_item" DROP CONSTRAINT "PK_result_item"`);
        await queryRunner.query(`ALTER TABLE "result_item" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "result_item" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "result_item" ADD CONSTRAINT "PK_bb389e7b9c53e9fc49ec625bf2f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "result_item" DROP COLUMN "resultId"`);
        await queryRunner.query(`ALTER TABLE "result_item" ADD "resultId" integer`);
        await queryRunner.query(`ALTER TABLE "result_item" DROP COLUMN "eventItemId"`);
        await queryRunner.query(`ALTER TABLE "result_item" ADD "eventItemId" integer`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" DROP CONSTRAINT "PK_result_member_based_item"`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" ADD CONSTRAINT "PK_58ac2719ca6913edd2d225c3519" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" DROP COLUMN "resultId"`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" ADD "resultId" integer`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" DROP COLUMN "eventItemId"`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" ADD "eventItemId" integer`);
        await queryRunner.query(`ALTER TABLE "result" DROP CONSTRAINT "PK_result"`);
        await queryRunner.query(`ALTER TABLE "result" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "result" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "result" ADD CONSTRAINT "PK_c93b145f3c2e95f6d9e21d188e2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "result" DROP COLUMN "clubId"`);
        await queryRunner.query(`ALTER TABLE "result" ADD "clubId" integer`);
        await queryRunner.query(`ALTER TABLE "result" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "result" ADD "eventId" integer`);
        await queryRunner.query(`ALTER TABLE "club" DROP CONSTRAINT "PK_club"`);
        await queryRunner.query(`ALTER TABLE "club" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "club" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "club" ADD CONSTRAINT "PK_79282481e036a6e0b180afa38aa" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "camp" DROP CONSTRAINT "PK_camp"`);
        await queryRunner.query(`ALTER TABLE "camp" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "camp" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "camp" ADD CONSTRAINT "PK_80bfb9f28fe9bdd60efd8866964" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "camp" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "camp" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "member_based_event_item" ADD CONSTRAINT "FK_dd9c566079710f189a8e45d8abf" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event" ADD CONSTRAINT "FK_bedaa1485073ba2e03985817ae5" FOREIGN KEY ("campId") REFERENCES "camp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_item" ADD CONSTRAINT "FK_240303484dbe00aa45b2cf86a2b" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_item" ADD CONSTRAINT "FK_3cd2c349b1fd39ab634baf46b32" FOREIGN KEY ("resultId") REFERENCES "result"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_item" ADD CONSTRAINT "FK_e5f8db752df4332895fce660feb" FOREIGN KEY ("eventItemId") REFERENCES "event_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" ADD CONSTRAINT "FK_8c40bd6944e3a842508d28736d9" FOREIGN KEY ("resultId") REFERENCES "result"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" ADD CONSTRAINT "FK_e6785c9f122f0a4fcfa7ec33525" FOREIGN KEY ("eventItemId") REFERENCES "member_based_event_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result" ADD CONSTRAINT "FK_f9284363a46ec833bef81689cf9" FOREIGN KEY ("clubId") REFERENCES "club"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result" ADD CONSTRAINT "FK_48eba0868e22f0409a99fa703ca" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "member_characteristic" ADD CONSTRAINT "FK_618c31baa866fda0990cdf32456" FOREIGN KEY ("clubId") REFERENCES "club"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "club" ADD CONSTRAINT "FK_f8e0685abaa926846cf01fbeeb5" FOREIGN KEY ("campId") REFERENCES "camp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "club" DROP CONSTRAINT "FK_f8e0685abaa926846cf01fbeeb5"`);
        await queryRunner.query(`ALTER TABLE "member_characteristic" DROP CONSTRAINT "FK_618c31baa866fda0990cdf32456"`);
        await queryRunner.query(`ALTER TABLE "result" DROP CONSTRAINT "FK_48eba0868e22f0409a99fa703ca"`);
        await queryRunner.query(`ALTER TABLE "result" DROP CONSTRAINT "FK_f9284363a46ec833bef81689cf9"`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" DROP CONSTRAINT "FK_e6785c9f122f0a4fcfa7ec33525"`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" DROP CONSTRAINT "FK_8c40bd6944e3a842508d28736d9"`);
        await queryRunner.query(`ALTER TABLE "result_item" DROP CONSTRAINT "FK_e5f8db752df4332895fce660feb"`);
        await queryRunner.query(`ALTER TABLE "result_item" DROP CONSTRAINT "FK_3cd2c349b1fd39ab634baf46b32"`);
        await queryRunner.query(`ALTER TABLE "event_item" DROP CONSTRAINT "FK_240303484dbe00aa45b2cf86a2b"`);
        await queryRunner.query(`ALTER TABLE "event" DROP CONSTRAINT "FK_bedaa1485073ba2e03985817ae5"`);
        await queryRunner.query(`ALTER TABLE "member_based_event_item" DROP CONSTRAINT "FK_dd9c566079710f189a8e45d8abf"`);
        await queryRunner.query(`ALTER TABLE "camp" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "camp" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "camp" DROP CONSTRAINT "PK_80bfb9f28fe9bdd60efd8866964"`);
        await queryRunner.query(`ALTER TABLE "camp" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "camp" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "camp" ADD CONSTRAINT "PK_camp" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "club" DROP CONSTRAINT "PK_79282481e036a6e0b180afa38aa"`);
        await queryRunner.query(`ALTER TABLE "club" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "club" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "club" ADD CONSTRAINT "PK_club" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "result" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "result" ADD "eventId" uuid`);
        await queryRunner.query(`ALTER TABLE "result" DROP COLUMN "clubId"`);
        await queryRunner.query(`ALTER TABLE "result" ADD "clubId" uuid`);
        await queryRunner.query(`ALTER TABLE "result" DROP CONSTRAINT "PK_c93b145f3c2e95f6d9e21d188e2"`);
        await queryRunner.query(`ALTER TABLE "result" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "result" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "result" ADD CONSTRAINT "PK_result" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" DROP COLUMN "eventItemId"`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" ADD "eventItemId" uuid`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" DROP COLUMN "resultId"`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" ADD "resultId" uuid`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" DROP CONSTRAINT "PK_58ac2719ca6913edd2d225c3519"`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" ADD CONSTRAINT "PK_result_member_based_item" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "result_item" DROP COLUMN "eventItemId"`);
        await queryRunner.query(`ALTER TABLE "result_item" ADD "eventItemId" uuid`);
        await queryRunner.query(`ALTER TABLE "result_item" DROP COLUMN "resultId"`);
        await queryRunner.query(`ALTER TABLE "result_item" ADD "resultId" uuid`);
        await queryRunner.query(`ALTER TABLE "result_item" DROP CONSTRAINT "PK_bb389e7b9c53e9fc49ec625bf2f"`);
        await queryRunner.query(`ALTER TABLE "result_item" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "result_item" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "result_item" ADD CONSTRAINT "PK_result_item" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "event_item" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "event_item" ADD "eventId" uuid`);
        await queryRunner.query(`ALTER TABLE "event_item" DROP CONSTRAINT "PK_0b8a384c1ee5dc33993b3004ae4"`);
        await queryRunner.query(`ALTER TABLE "event_item" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "event_item" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "event_item" ADD CONSTRAINT "PK_event_item" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "campId"`);
        await queryRunner.query(`ALTER TABLE "event" ADD "campId" uuid`);
        await queryRunner.query(`ALTER TABLE "event" ALTER COLUMN "maxScore" SET DEFAULT '100'`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "event" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "event" DROP CONSTRAINT "PK_30c2f3bbaf6d34a55f8ae6e4614"`);
        await queryRunner.query(`ALTER TABLE "event" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "event" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "event" ADD CONSTRAINT "PK_event" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "member_based_event_item" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "member_based_event_item" ADD "eventId" uuid`);
        await queryRunner.query(`ALTER TABLE "member_based_event_item" DROP CONSTRAINT "PK_99592168c7bd73e9366b2b05f0e"`);
        await queryRunner.query(`ALTER TABLE "member_based_event_item" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "member_based_event_item" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "member_based_event_item" ADD CONSTRAINT "PK_member_based_event_item" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "PK_user" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "club" DROP COLUMN "campId"`);
        await queryRunner.query(`ALTER TABLE "club" DROP COLUMN "isPaid"`);
        await queryRunner.query(`ALTER TABLE "club" DROP COLUMN "registrationFee"`);
        await queryRunner.query(`ALTER TABLE "club" DROP COLUMN "companionsCount"`);
        await queryRunner.query(`ALTER TABLE "club" DROP COLUMN "economsCount"`);
        await queryRunner.query(`ALTER TABLE "club" DROP COLUMN "minorsCount"`);
        await queryRunner.query(`ALTER TABLE "club" DROP COLUMN "guestsCount"`);
        await queryRunner.query(`ALTER TABLE "club" DROP COLUMN "participantsCount"`);
        await queryRunner.query(`ALTER TABLE "club" ADD "foundationDate" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "club" ADD "slogan" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event" ADD "endDate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event" ADD "startDate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`DROP TABLE "member_characteristic"`);
        await queryRunner.query(`CREATE INDEX "IDX_result_event" ON "result" ("eventId") `);
        await queryRunner.query(`CREATE INDEX "IDX_result_club" ON "result" ("clubId") `);
        await queryRunner.query(`CREATE INDEX "IDX_result_member_based_item_event_item" ON "result_member_based_item" ("eventItemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_result_member_based_item_result" ON "result_member_based_item" ("resultId") `);
        await queryRunner.query(`CREATE INDEX "IDX_result_item_event_item" ON "result_item" ("eventItemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_result_item_result" ON "result_item" ("resultId") `);
        await queryRunner.query(`CREATE INDEX "IDX_event_item_event" ON "event_item" ("eventId") `);
        await queryRunner.query(`CREATE INDEX "IDX_event_camp" ON "event" ("campId") `);
        await queryRunner.query(`CREATE INDEX "IDX_member_based_event_item_event" ON "member_based_event_item" ("eventId") `);
        await queryRunner.query(`ALTER TABLE "result" ADD CONSTRAINT "FK_result_event" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result" ADD CONSTRAINT "FK_result_club" FOREIGN KEY ("clubId") REFERENCES "club"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" ADD CONSTRAINT "FK_result_member_based_item_event_item" FOREIGN KEY ("eventItemId") REFERENCES "member_based_event_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_member_based_item" ADD CONSTRAINT "FK_result_member_based_item_result" FOREIGN KEY ("resultId") REFERENCES "result"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_item" ADD CONSTRAINT "FK_result_item_event_item" FOREIGN KEY ("eventItemId") REFERENCES "event_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_item" ADD CONSTRAINT "FK_result_item_result" FOREIGN KEY ("resultId") REFERENCES "result"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_item" ADD CONSTRAINT "FK_event_item_event" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event" ADD CONSTRAINT "FK_event_camp" FOREIGN KEY ("campId") REFERENCES "camp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "member_based_event_item" ADD CONSTRAINT "FK_member_based_event_item_event" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
